# Site settings
title: fkacam
email: cam@fkacam.com
description: > # this means to ignore newlines until "baseurl:"
  Some thoughts on startups, health and medicine, reasoning, psychology, cryptography, and netsec.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fkacam.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
